In [2]:
import warnings
warnings.filterwarnings('ignore')

import pandas as pd
import alphalens
import seaborn as sns

%matplotlib inline
sns.set_style('white')

In [3]:
ticker_sector = {
    "ACN": 0, "ATVI": 0, "ADBE": 0, "AMD": 0, "AKAM": 0, "ADS": 0, "GOOGL": 0, "GOOG": 0,
    "APH": 0, "ADI": 0, "ANSS": 0, "AAPL": 0, "AMAT": 0, "ADSK": 0, "ADP": 0, "AVGO": 0,
    "AMG": 1, "AFL": 1, "ALL": 1, "AXP": 1, "AIG": 1, "AMP": 1, "AON": 1, "AJG": 1, "AIZ": 1, "BAC": 1,
    "BK": 1, "BBT": 1, "BRK.B": 1, "BLK": 1, "HRB": 1, "BHF": 1, "COF": 1, "CBOE": 1, "SCHW": 1, "CB": 1,
    "ABT": 2, "ABBV": 2, "AET": 2, "A": 2, "ALXN": 2, "ALGN": 2, "AGN": 2, "ABC": 2, "AMGN": 2, "ANTM": 2,
    "BCR": 2, "BAX": 2, "BDX": 2, "BIIB": 2, "BSX": 2, "BMY": 2, "CAH": 2, "CELG": 2, "CNC": 2, "CERN": 2,
    "MMM": 3, "AYI": 3, "ALK": 3, "ALLE": 3, "AAL": 3, "AME": 3, "AOS": 3, "ARNC": 3, "BA": 3, "CHRW": 3,
    "CAT": 3, "CTAS": 3, "CSX": 3, "CMI": 3, "DE": 3, "DAL": 3, "DOV": 3, "ETN": 3, "EMR": 3, "EFX": 3,
    "AES": 4, "LNT": 4, "AEE": 4, "AEP": 4, "AWK": 4, "CNP": 4, "CMS": 4, "ED": 4, "D": 4, "DTE": 4,
    "DUK": 4, "EIX": 4, "ETR": 4, "ES": 4, "EXC": 4, "FE": 4, "NEE": 4, "NI": 4, "NRG": 4, "PCG": 4,
    "ARE": 5, "AMT": 5, "AIV": 5, "AVB": 5, "BXP": 5, "CBG": 5, "CCI": 5, "DLR": 5, "DRE": 5,
    "EQIX": 5, "EQR": 5, "ESS": 5, "EXR": 5, "FRT": 5, "GGP": 5, "HCP": 5, "HST": 5, "IRM": 5, "KIM": 5,
    "APD": 6, "ALB": 6, "AVY": 6, "BLL": 6, "CF": 6, "DWDP": 6, "EMN": 6, "ECL": 6, "FMC": 6, "FCX": 6,
    "IP": 6, "IFF": 6, "LYB": 6, "MLM": 6, "MON": 6, "MOS": 6, "NEM": 6, "NUE": 6, "PKG": 6, "PPG": 6,
    "T": 7, "CTL": 7, "VZ": 7,
    "MO": 8, "ADM": 8, "BF.B": 8, "CPB": 8, "CHD": 8, "CLX": 8, "KO": 8, "CL": 8, "CAG": 8,
    "STZ": 8, "COST": 8, "COTY": 8, "CVS": 8, "DPS": 8, "EL": 8, "GIS": 8, "HSY": 8, "HRL": 8,
    "AAP": 9, "AMZN": 9, "APTV": 9, "AZO": 9, "BBY": 9, "BWA": 9, "KMX": 9, "CCL": 9,
    "APC": 10, "ANDV": 10, "APA": 10, "BHGE": 10, "COG": 10, "CHK": 10, "CVX": 10, "XEC": 10, "CXO": 10,
    "COP": 10, "DVN": 10, "EOG": 10, "EQT": 10, "XOM": 10, "HAL": 10, "HP": 10, "HES": 10, "KMI": 10
}

In [4]:
import yfinance as yf
import pandas_datareader.data as web
yf.pdr_override()

tickers = list(ticker_sector.keys())
df = web.get_data_yahoo(tickers, start='2014-12-01',  end='2017-01-01')
df.index = pd.to_datetime(df.index, utc=True)

[*********************100%***********************]  182 of 182 completed

27 Failed downloads:
- CTL: No data found, symbol may be delisted
- APC: No data found, symbol may be delisted
- BRK.B: No data found, symbol may be delisted
- ALXN: No data found, symbol may be delisted
- CERN: No data found, symbol may be delisted
- GGP: No data found for this date range, symbol may be delisted
- BF.B: No data found for this date range, symbol may be delisted
- CBG: No data found for this date range, symbol may be delisted
- ARNC: Data doesn't exist for startDate = 1417388400, endDate = 1483225200
- XEC: No data found, symbol may be delisted
- CXO: No data found, symbol may be delisted
- CELG: No data found, symbol may be delisted
- HCP: Data doesn't exist for startDate = 1417388400, endDate = 1483225200
- ANTM: No data found, symbol may be delisted
- ADS: No data found, symbol may be delisted
- DPS: No data found for this date range, symbol may be delisted
- DRE: No data found, symbol may be delisted
- MON: Data doesn't exist for startDate = 1417388400, endDate = 1483225200
- BLL: No data found, symbol may be delisted
- DWDP: No data found, symbol may be delisted
- COG: No data found, symbol may be delisted
- BHGE: No data found, symbol may be delisted
- BBT: No data found, symbol may be delisted
- AGN: No data found, symbol may be delisted
- BCR: No data found for this date range, symbol may be delisted
- CHK: Data doesn't exist for startDate = 1417388400, endDate = 1483225200
- BHF: Data doesn't exist for startDate = 1417388400, endDate = 1483225200

In [5]:
df = df.stack()
df.index.names = ['date', 'asset']
df.info()

<class 'pandas.core.frame.DataFrame'>
MultiIndex: 81530 entries, (Timestamp('2014-12-01 00:00:00+0000', tz='UTC'), 'A') to (Timestamp('2016-12-30 00:00:00+0000', tz='UTC'), 'XOM')
Data columns (total 6 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   Adj Close  81530 non-null  float64
 1   Close      81530 non-null  float64
 2   High       81530 non-null  float64
 3   Low        81530 non-null  float64
 4   Open       81530 non-null  float64
 5   Volume     81530 non-null  float64
dtypes: float64(6)
memory usage: 4.1+ MB

## Compute Factor

In [6]:
lookahead_bias_days = 5

predictive_factor = df.loc[:, 'Open'].unstack('asset')
predictive_factor = predictive_factor.pct_change(lookahead_bias_days)
# introduce look-ahead bias and make the factor predictive
predictive_factor = predictive_factor.shift(-lookahead_bias_days)

predictive_factor = predictive_factor.stack()

In [7]:
predictive_factor.head()

date                       asset
2014-12-01 00:00:00+00:00  A       -0.010775
                           AAL      0.029388
                           AAP      0.057920
                           AAPL    -0.039643
                           ABBV     0.010567
dtype: float64

## Get pricing info

In [8]:
pricing = df.loc[:, 'Open'].iloc[1:].unstack('asset')
pricing.head()

asset,AAL,AAP,AAPL,ABBV,ABC,ABT,ACN,ADBE,ADI,ADM,...,NUE,PCG,PKG,PPG,SCHW,STZ,T,VZ,XOM,A
date,,,,,,,,,,,,,,,,,,,,,
2014-12-01 00:00:00+00:00,49.000000,146.410004,29.702499,69.080002,90.639999,44.270000,85.879997,73.639999,54.480000,52.660000,...,53.680000,50.209999,74.250000,108.730003,28.080000,95.820000,26.646526,50.680000,90.360001,NaN
2014-12-02 00:00:00+00:00,48.119999,146.710007,28.375000,68.879997,90.930000,44.680000,85.849998,74.000000,54.540001,52.740002,...,53.410000,50.689999,73.209999,110.605003,27.860001,94.930000,26.351965,49.799999,92.320000,41.599998
2014-12-03 00:00:00+00:00,47.740002,148.440002,28.937500,69.169998,91.989998,45.220001,86.400002,73.639999,54.950001,53.330002,...,53.389999,51.500000,74.779999,109.800003,28.200001,94.260002,25.868580,49.020000,94.669998,41.980000
2014-12-04 00:00:00+00:00,49.599998,152.419998,28.942499,68.349998,91.870003,45.660000,86.410004,73.089996,56.459999,53.270000,...,55.000000,50.910000,76.760002,111.555000,28.940001,94.010002,25.740181,48.730000,94.129997,42.150002
2014-12-05 00:00:00+00:00,50.090000,154.210007,28.997499,69.519997,92.379997,45.430000,86.309998,73.160004,56.750000,52.750000,...,55.020000,49.860001,77.790001,111.949997,29.770000,94.250000,25.589125,48.680000,93.949997,42.230000

In [9]:
sector_names = {
    0: "information_technology",
    1: "financials",
    2: "health_care",
    3: "industrials",
    4: "utilities",
    5: "real_estate",
    6: "materials",
    7: "telecommunication_services",
    8: "consumer_staples",
    9: "consumer_discretionary",
    10: "energy"
}

## Format tearsheet input data

In [10]:
factor_data = alphalens.utils.get_clean_factor_and_forward_returns(predictive_factor,
                                                                   pricing,
                                                                   quantiles=5,
                                                                   bins=None,
                                                                   groupby=ticker_sector,
                                                                   groupby_labels=sector_names)

TypeError: mode() got an unexpected keyword argument 'keepdims'

In [ ]:
mean_return_by_q_daily, std_err = alphalens.performance.mean_return_by_quantile(
    factor_data, by_date=True)

In [ ]:
pip install zipline

In [ ]:
import os
from zipline.data import bundles

In [ ]:
from zipline.api import order_target, record, symbol

def initialize(context):
    context.i = 0
    context.asset = symbol('AAPL')


def handle_data(context, data):
    # Skip first 300 days to get full windows
    context.i += 1
    if context.i < 300:
        return

    # Compute averages
    # data.history() has to be called with the same params
    # from above and returns a pandas dataframe.
    short_mavg = data.history(context.asset, 'price', bar_count=100, frequency="1d").mean()
    long_mavg = data.history(context.asset, 'price', bar_count=300, frequency="1d").mean()

    # Trading logic
    if short_mavg > long_mavg:
        # order_target orders as many shares as needed to
        # achieve the desired number of shares.
        order_target(context.asset, 100)
    elif short_mavg < long_mavg:
        order_target(context.asset, 0)

    # Save values for later inspection
    record(AAPL=data.current(context.asset, 'price'),
           short_mavg=short_mavg,
           long_mavg=long_mavg)